# Generated by Django 2.2.4 on 2020-12-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=300)),
                ('movie_release_date', models.DateField()),
                ('movie_summary', models.CharField(max_length=10000)),
            ],
        ),
    ]
